import { products, owner } from '../lib/data'
import { Search, ShoppingCart, Heart, User, Truck, ShieldCheck, MessageCircle, Star } from 'lucide-react'

function Logo(){ return <div className="flex items-center gap-3"><div className="h-11 w-11 rounded-2xl bg-emeraldBrand grid place-items-center shadow-lg shadow-emerald-500/20"><span className="text-2xl font-black">V</span></div><div><div className="text-xl font-black tracking-[0.24em]">VELORA</div><div className="text-xs text-emerald-200">Online Store</div></div></div> }
export default function Home(){ return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#0F766E_0%,#0B1120_38%,#050816_100%)]">
<header className="mx-auto max-w-7xl px-5 py-5"><div className="flex items-center justify-between gap-5"><Logo/><div className="hidden md:flex flex-1 max-w-xl items-center gap-2 rounded-2xl border border-emerald-400/30 bg-white/10 px-4 py-3"><Search size={18}/><input className="w-full bg-transparent outline-none placeholder:text-emerald-100" placeholder="Найти товар..." /></div><nav className="flex items-center gap-4 text-sm"><span className="hidden lg:flex items-center gap-1"><Truck size={16}/> Доставка по РФ</span><Heart/><ShoppingCart/><User/></nav></div></header>
<section className="mx-auto max-w-7xl px-5 py-14 grid lg:grid-cols-2 gap-10 items-center"><div><div className="mb-5 inline-flex rounded-full border border-emerald-400/30 bg-emerald-500/10 px-4 py-2 text-emerald-100">🚚 Доставка по всей России</div><h1 className="text-5xl md:text-7xl font-black leading-tight">Стиль. <span className="text-emeraldAccent">Качество.</span> Выбор.</h1><p className="mt-6 text-lg text-slate-300 max-w-xl">VELORA — современный интернет-магазин товаров для дома, стиля и технологий с удобной оплатой, личным кабинетом и поддержкой.</p><div className="mt-8 flex gap-4"><button className="rounded-2xl bg-emeraldAccent px-6 py-4 font-bold text-night">Перейти в каталог</button><button className="rounded-2xl border border-emerald-300/30 px-6 py-4 font-bold">Новинки</button></div></div><div className="card p-6"><div className="rounded-3xl bg-gradient-to-br from-emerald-400/40 to-slate-900 p-8 min-h-[360px]"><div className="mx-auto h-48 w-48 rounded-[42px] border border-emerald-200/40 bg-emerald-500/20 grid place-items-center text-8xl font-black shadow-2xl shadow-emerald-500/20">V</div><div className="mt-8 grid grid-cols-3 gap-3 text-center text-sm"><div className="card p-3"><ShieldCheck className="mx-auto mb-2"/>Безопасная оплата</div><div className="card p-3"><Truck className="mx-auto mb-2"/>СДЭК / Почта</div><div className="card p-3"><MessageCircle className="mx-auto mb-2"/>Поддержка</div></div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-10"><h2 className="text-3xl font-black mb-6">Хиты продаж</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{products.map(p=><article key={p.id} className="card p-5"><div className="h-44 rounded-2xl bg-gradient-to-br from-emerald-400/30 to-white/5 grid place-items-center text-5xl font-black">V</div><div className="mt-4 text-sm text-emerald-200">{p.category}</div><h3 className="mt-1 font-bold min-h-[48px]">{p.name}</h3><div className="mt-3 flex justify-between items-center"><b>{p.price.toLocaleString('ru-RU')} ₽</b><span className="flex items-center gap-1 text-sm"><Star size={15}/> {p.rating}</span></div><button className="mt-4 w-full rounded-xl bg-emeraldBrand py-3 font-bold">В корзину</button></article>)}</div></section>
<footer className="mx-auto max-w-7xl px-5 py-10 text-slate-300 border-t border-emerald-400/20"><Logo/><div className="mt-5 text-sm">Владелец: {owner.name} · Email: {owner.email} · Telegram: {owner.telegram}</div><div className="mt-2 text-sm">© 2026 VELORA. Все права защищены.</div></footer>
</main> }
