create table profiles (
  id uuid primary key,
  email text unique not null,
  full_name text,
  role text default 'USER',
  created_at timestamp with time zone default now()
);

create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price integer not null,
  category text,
  stock integer default 0,
  image_url text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid,
  status text default 'NEW',
  total integer default 0,
  customer_name text,
  customer_phone text,
  customer_email text,
  address text,
  tracking_number text,
  created_at timestamp with time zone default now()
);

-- Главный владелец должен иметь role = 'OWNER'
-- Email владельца: vi1344060@gmail.com
