create table if not exists profiles (id uuid primary key, email text unique, role text default 'USER', created_at timestamptz default now());
create table if not exists products (id bigint generated by default as identity primary key, name text not null, price integer not null, category text, image text, stock integer default 0, created_at timestamptz default now());
create table if not exists reviews (id bigint generated by default as identity primary key, product_id bigint, user_name text, rating integer, text text, created_at timestamptz default now());
create table if not exists orders (id bigint generated by default as identity primary key, user_email text, total integer, status text default 'new', created_at timestamptz default now());
