import Link from 'next/link'
import { ShoppingCart, Heart, User, Search, Star, Truck, ShieldCheck, MessageCircle, LayoutDashboard } from 'lucide-react'
import { owner } from './data'
export function Logo(){return <Link href="/" className="flex items-center gap-3"><div className="h-12 w-12 rounded-2xl bg-gradient-to-br from-emeraldMain to-emeraldAccent flex items-center justify-center text-3xl font-black shadow-lg">V</div><div><div className="text-2xl font-black tracking-[.22em]">VELORA</div><div className="text-xs text-emerald-300 tracking-[.22em]">Online Store</div></div></Link>}
export function Header(){return <header className="sticky top-0 z-50 border-b border-emerald-500/20 bg-night/90 backdrop-blur"><div className="mx-auto max-w-7xl px-5 py-3 flex items-center justify-between gap-4"><Logo/><div className="hidden md:flex items-center gap-2 rounded-2xl border border-emerald-500/25 bg-black/20 px-4 py-2 w-96"><Search size={18}/><input className="bg-transparent outline-none w-full text-sm" placeholder="Найти товар..."/></div><nav className="flex items-center gap-3 text-sm"><Link href="/catalog">Каталог</Link><Link href="/reviews">Отзывы</Link><Link href="/cart"><ShoppingCart size={20}/></Link><Link href="/profile"><User size={20}/></Link><Link href="/admin" className="text-emerald-300"><LayoutDashboard size={20}/></Link></nav></div></header>}
export function Footer(){return <footer className="mt-16 border-t border-emerald-500/20"><div className="mx-auto max-w-7xl px-5 py-10 grid md:grid-cols-4 gap-8"><div><Logo/><p className="mt-4 text-sm text-slate-300">Стиль. Качество. Выбор. Доставка по всей России.</p></div><div><h4 className="font-bold mb-3">Покупателям</h4><p className="text-sm text-slate-300">Доставка<br/>Возврат<br/>Оплата<br/>Гарантия</p></div><div><h4 className="font-bold mb-3">Контакты</h4><p className="text-sm text-slate-300">{owner.email}<br/>{owner.telegram}<br/>Поддержка 24/7</p></div><div><h4 className="font-bold mb-3">Мы принимаем</h4><p className="text-sm text-slate-300">Visa · Mastercard · МИР · СБП · SberPay</p></div></div><div className="text-center text-xs text-slate-500 pb-6">© 2026 VELORA. Все права защищены.</div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/><main className="mx-auto max-w-7xl px-5">{children}</main><Footer/></>}
export function ProductCard({p}:any){return <div className="card p-4 hover:border-emerald-400/60 transition"><Link href={`/product/${p.id}`}><div className="h-44 rounded-2xl bg-gradient-to-br from-slate-900 to-emerald-900/40 flex items-center justify-center text-7xl">{p.image}</div><div className="mt-4 flex justify-between gap-3"><h3 className="font-bold">{p.name}</h3><Heart size={20}/></div><div className="mt-2 flex items-center gap-2 text-amber-400"><Star size={16} fill="currentColor"/> <span className="text-sm text-slate-300">{p.rating} ({p.reviews})</span></div><div className="mt-3 text-2xl font-black">{p.price.toLocaleString('ru-RU')} ₽ <span className="text-sm line-through text-slate-500">{p.oldPrice.toLocaleString('ru-RU')} ₽</span></div></Link><button className="btn btn-primary w-full mt-4">В корзину</button></div>}
export function TrustBar(){return <div className="grid md:grid-cols-4 gap-4 my-8"><div className="glass rounded-2xl p-4 flex gap-3"><ShieldCheck className="text-emerald-300"/>Безопасная оплата</div><div className="glass rounded-2xl p-4 flex gap-3"><Truck className="text-emerald-300"/>Доставка по РФ</div><div className="glass rounded-2xl p-4 flex gap-3"><Star className="text-emerald-300"/>Проверенное качество</div><div className="glass rounded-2xl p-4 flex gap-3"><MessageCircle className="text-emerald-300"/>Поддержка 24/7</div></div>}
